-- The following data is synthetic data generated by Copilot AI
-- Users --

INSERT INTO Users VALUES
(1, 'Alex', 'Taylor', 'alex.taylor@test.local'),
(2, 'Jordan', 'Morgan', 'jordan.morgan@test.local'),
(3, 'Casey', 'Parker', 'casey.parker@test.local'),
(4, 'Riley', 'Cameron', 'riley.cameron@test.local'),
(5, 'Avery', 'Reed', 'avery.reed@test.local');

INSERT INTO Project VALUES
(1, 'Project Alpha', 1),
(2, 'Project Bravo', 1),
(3, 'Project Charlie', 2),
(4, 'Project Delta', 3),
(5, 'Project Echo', 4),
(6, 'Project Foxtrot', 5);

INSERT INTO SecurityControl VALUES
('AC-1', 'Access Control Policy'),
('AC-2', 'Account Management'),
('AC-7', 'Unsuccessful Logon Attempts'),
('AU-2', 'Audit Events'),
('AU-6', 'Audit Review and Analysis'),
('CM-2', 'Baseline Configuration'),
('CM-6', 'Configuration Settings'),
('IA-2', 'Identification and Authentication'),
('IR-4', 'Incident Handling'),
('RA-5', 'Vulnerability Monitoring'),
('SC-4', 'Information in Shared Resources'),
('SC-7', 'Boundary Protection'),
('SI-2', 'Flaw Remediation');

INSERT INTO ProjectSecurityControlStatus VALUES
(1, 'AC-1', 'Met'),
(1, 'AC-2', 'Met'),
(1, 'AC-7', 'Partially Met'),
(1, 'SC-7', 'Met'),
(1, 'RA-5', 'Partially Met'),

(2, 'AC-1', 'Not Met'),
(2, 'IA-2', 'Met'),
(2, 'SC-7', 'Partially Met'),
(2, 'RA-5', 'Not Met'),
(2, 'IR-4', 'Partially Met'),

(3, 'AC-1', 'Met'),
(3, 'IA-2', 'Met'),
(3, 'CM-2', 'Met'),
(3, 'CM-6', 'Partially Met'),
(3, 'SI-2', 'Not Met'),

(4, 'SC-4', 'Met'),
(4, 'SC-7', 'Met'),
(4, 'AU-2', 'Met'),
(4, 'AU-6', 'Partially Met'),
(4, 'IR-4', 'Not Met'),

(5, 'IA-2', 'Partially Met'),
(5, 'SC-7', 'Met'),
(5, 'CM-2', 'Met'),
(5, 'CM-6', 'Partially Met'),
(5, 'RA-5', 'Not Met'),

(6, 'AC-2', 'Not Met'),
(6, 'AU-2', 'Partially Met'),
(6, 'RA-5', 'Met'),
(6, 'SC-4', 'Met'),
(6, 'SI-2', 'Partially Met');

